---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-blast
      component: postgres
  template:
    metadata:
      labels:
        app: quarkus-blast
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres-quarkus-blast:latest
          env:
            - name: PGDATA
              value: /work/data
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: blast-secret
                  key: db-database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blast-secret
                  key: db-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blast-secret
                  key: db-user
          ports:
            - containerPort: 5432
              name: db-port
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: data-postgres-1
              mountPath: /work
      volumes:
        - name: data-postgres-1
          persistentVolumeClaim:
            claimName: data-postgres-1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: quarkus-blast
    component: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-postgres-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi